version: '3'

services:

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    restart: always
    volumes:
      - /home/aleksandr/IdeaProjects/at_tests/influxdb_data:/var/lib/influxdb_data
      - /home/aleksandr/IdeaProjects/at_tests/influxdb_backup:/var/backups

  grafana:
    image: grafana/grafana:7.2.1
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./grafana_data:/var/lib/grafana

