version: '3.7'

services:

  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    volumes:
    - ~/prometheus:/etc/prometheus
    ports:
      - 9090:9090
    links:
      - pushgateway:pushgateway
    depends_on:
      - pushgateway

    restart: always

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: always
    expose:
      - 9091
    ports:
      - 9091:9091
