version: '3.7'

services:

  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    volumes:
    - ~/prometheus:/etc/prometheus
    ports:
      - 9090:9090
    links:
      - pushgateway:pushgateway
    depends_on:
      - pushgateway

    restart: always

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: always
    expose:
      - 9091
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana:8.5.13
    container_name: grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
#    volumes:
#      - grafana_data:/var/lib/grafana
    restart: always